### ISSUE TITLE
Running into:  ERROR  Unknown option: 'interactive'

### ISSUE THREAD

**Issue by careyer** [rigwild/raspberry-instock-check#1]
Hi there,

thanks for the awesome project. Sadly I run into this problem:
![grafik](https://user-images.githubusercontent.com/6156251/166639009-ea33a532-b617-4155-b693-ee888757ccba.png)

Any ideas?
Best regards

**Comment by rigwild** [comment]
Hi, It's `i` (or `pnpm install`) not `-i` 😅

-------- Original Message --------

**Comment by careyer** [comment]
Thank you very much! Indeed my fault... 🤦 
Can you please explain what `TELEGRAM_CURRENTLY_IN_STOCK_MESSAGE_ID=<telegram_message_id_to_live_update_current_stock> \` is good for and what parameter does it expect? Could not find ino on it anywhere. Thanks again!

**Comment by rigwild** [comment]
`TELEGRAM_CURRENTLY_IN_STOCK_MESSAGE_ID` is the message id of the live update stock message

**It is optional**

The bot will update this message with current stock info. Bot must be able to edit the specific message. To get the id, right click copy post link and pick the number at the end.

Example in the public channel https://t.me/raspberry_alert/516

![image](https://user-images.githubusercontent.com/26366184/166701075-092414e9-6238-4c18-9084-eaa2ac22293b.png)

**Comment by rigwild** [comment]
I updated the readme with more info 🙏
